In [4]:
print('Welcome to Numpy, the numerical python...')

Welcome to Numpy, the numerical python...


In [9]:
import numpy as np
my_list = [1,2,3,4,5]

my_list



[1, 2, 3, 4, 5]

In [12]:
my_array = np.array(my_list)

my_array

array([1, 2, 3, 4, 5])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.linspace(0,2,11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])