<a href="https://colab.research.google.com/github/mamud1977/bootup/blob/main/my_tensorflow%202.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensorflow 2.0.....**

# Tensorflow 2.0.

In [19]:
!pip install tensorflow-gpu==2.8.4

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.1/498.1 MB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 40.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 40.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 61.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 462.3/462.3 kB 25.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 54.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 28.4 MB/s eta 0:00:00
  Attempting uninstall: keras
    Found existing installation: keras 3.4.1
    Uninstalling keras-3.4.1:
      Successfully uninstalled keras-3.4.1
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.7.2
    Uninstalling tensorboard-data-server-0.7.2:
      Successfully uninstalled tensorboard-data-server-0.7.2
  At

In [20]:
import tensorflow as tf
import numpy as np

print(tf.__version__)


print('TF Constant.....')
tensor_conc = tf.constant([[1,2],[3,4]])
x = tensor_conc.numpy()
print('TF Constant:',x)

np_array = np.array([[23,44,55],[333,33,7]])
tensor_from_numpy = tf.constant(np_array)
x = tensor_from_numpy.numpy()
print('tensor_from_numpy:',x)

print('TF Variable.....')
tensor_var = tf.Variable([[23,44,55],[333,33,7]])
print('Initial :',tensor_var)

tensor_var = tensor_var[1,2].assign(200)
print('Updated :',tensor_var)

tf_c = tf.constant([[1,2],[3,4]])
print('Initial constant:',tf_c)

tf_c = tf_c + 10

print('Initial + 10 :',tf_c)

tf_c = tf_c * 2
print('Mult:',tf_c)

tf_c = tf.constant([[1,2],[3,4]])
tf_c =np.square(tf_c)
print('Square:',tf_c)

tf_c =np.sqrt(tf_c)
print('Sqrt:',tf_c)

tf_c =np.log(tf_c)
print('Log:',tf_c)



tfv1 = tf.Variable([[1,2],[3,4]])
tfv2 = tf.Variable([[2,0],[1,1]])


print('Dot product of two tensor:')
y = np.dot(tfv1, tfv2)
print(y)

s = tf.constant('Hello World!!!')
print('Length:',tf.strings.length(s))
print("Unicode Decode:",tf.strings.unicode_decode(s,"UTF8"))


tf_array = tf.constant(["Big","Class","Room"])

for s in tf_array:
  print(s)
  print(type(s))


2.8.4
TF Constant.....
TF Constant: [[1 2]
 [3 4]]
tensor_from_numpy: [[ 23  44  55]
 [333  33   7]]
TF Variable.....
Initial : <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 23,  44,  55],
       [333,  33,   7]], dtype=int32)>
Updated : <tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 23,  44,  55],
       [333,  33, 200]], dtype=int32)>
Initial constant: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Initial + 10 : tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
Mult: tf.Tensor(
[[22 24]
 [26 28]], shape=(2, 2), dtype=int32)
Square: [[ 1  4]
 [ 9 16]]
Sqrt: [[1. 2.]
 [3. 4.]]
Log: [[0.         0.69314718]
 [1.09861229 1.38629436]]
Dot product of two tensor:
[[ 4  2]
 [10  4]]
Length: tf.Tensor(14, shape=(), dtype=int32)
Unicode Decode: tf.Tensor([ 72 101 108 108 111  32  87 111 114 108 100  33  33  33], shape=(14,), dtype=int32)
tf.Tensor(b'Big', shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.EagerTensor'>