<a href="https://colab.research.google.com/github/mamud1977/bootup/blob/main/my_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensorflow.....**

In [ ]:
print('Tensorflow')

Tensorflow


In [ ]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

hello = tf.constant("Hellooooooooooooo ")
world = tf.constant("World! ")

type (hello)

sess = tf.compat.v1.Session()
result = sess.run(hello+world)

result

b'Hellooooooooooooo World! '

In [ ]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

a = tf.constant(10)
b = tf.constant(450)
sess = tf.compat.v1.Session()
result = sess.run(a+b)
result

460

In [ ]:
const = tf.constant(10)

fill_mat = tf.fill( (4,4), 10)

fill_zero = tf.zeros((4,4))

myrandn = tf.random.normal((4,4), mean = 2, stddev =0.5)

my_ops = [const, fill_mat, fill_zero, myrandn]

sess = tf.compat.v1.Session()
result = sess.run(const)
result


10

In [ ]:
sess = tf.compat.v1.Session()
result = sess.run(fill_mat )
result

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)

In [ ]:
sess = tf.compat.v1.Session()
result = sess.run(fill_zero)
result

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [ ]:
sess = tf.compat.v1.Session()
result = sess.run(myrandn)
result

array([[1.1881309, 2.546825 , 2.0361106, 2.0137334],
       [2.539907 , 2.474639 , 2.2981424, 3.2171803],
       [2.0480635, 2.4358706, 1.7014809, 2.3479867],
       [1.4695742, 0.9597193, 2.6892915, 2.066409 ]], dtype=float32)

In [ ]:
a = tf.constant([[1,2],
                [3,4],
                 [4,6]])

b = tf.constant([[7,2,8],
                [3,4,1]])

result = tf.matmul(a,b)

sess = tf.compat.v1.Session()
result = sess.run(tf.matmul(a,b))
result

array([[13, 10, 10],
       [33, 22, 28],
       [46, 32, 38]], dtype=int32)

In [ ]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

n1 = tf.constant(3)
n2 = tf.constant(4)

n3 = n1 +  n2

sess = tf.compat.v1.Session()
result = sess.run(n3)
result

g = tf.Graph()
print (g)

graph1 = tf.compat.v1.get_default_graph()
print (graph1)

graph2 = tf.Graph()
print (graph2)

with graph2.as_default():
  print(graph2 is tf.compat.v1.get_default_graph())

print(graph2 is tf.compat.v1.get_default_graph())

True
False


In [ ]:
import tensorflow.compat.v1 as tf


tf.compat.v1.disable_eager_execution()

my_tensor = tf.random.uniform((4,4),minval=0, maxval =1, dtype='float32')

sess = tf.compat.v1.Session()
result = sess.run(my_tensor)
result

my_var = tf.Variable(initial_value = my_tensor)

init = tf.compat.v1.global_variables_initializer()

sess.run(init )
sess.run(my_var)

ph = tf.placeholder(tf.float32, None, None)
ph




<tf.Tensor 'Placeholder_3:0' shape=<unknown> dtype=float32>

In [ ]:
import numpy as np
import tensorflow.compat.v1 as tf

np.random.seed(100)
tf.set_random_seed(100)

rand_a = np.random.uniform(0,10,(5,5))
print(rand_a)

rand_b = np.random.uniform(0,10,(5,1))
print(rand_b)

a = tf.placeholder(tf.float32, None, None)
b = tf.placeholder(tf.float32, None, None)

add_op = a + b

mult_op = a * b

sess = tf.compat.v1.Session()
result = sess.run(mult_op, feed_dict = {a:rand_a, b:rand_b})
result







[[5.43404942 2.78369385 4.24517591 8.44776132 0.04718856]
 [1.21569121 6.70749085 8.25852755 1.3670659  5.75093329]
 [8.91321954 2.09202122 1.8532822  1.0837689  2.19697493]
 [9.78623785 8.11683149 1.71941013 8.16224749 2.74073747]
 [4.31704184 9.4002982  8.17649379 3.3611195  1.75410454]]
[[3.72832046]
 [0.05688507]
 [2.52426353]
 [7.95662508]
 [0.15254971]]


array([[2.0259878e+01, 1.0378502e+01, 1.5827375e+01, 3.1495962e+01,
        1.7593408e-01],
       [6.9154687e-02, 3.8155612e-01, 4.6978697e-01, 7.7765644e-02,
        3.2714227e-01],
       [2.2499315e+01, 5.2808132e+00, 4.6781731e+00, 2.7357185e+00,
        5.5457439e+00],
       [7.7865425e+01, 6.4582588e+01, 1.3680702e+01, 6.4943947e+01,
        2.1807020e+01],
       [6.5856349e-01, 1.4340128e+00, 1.2473217e+00, 5.1273781e-01,
        2.6758814e-01]], dtype=float32)

In [43]:
n_features = 10
n_dense_neurons = 3

x = tf.placeholder(tf.float32, (None, n_features))
W = tf.Variable(tf.random_normal([n_features,n_dense_neurons]))
b = tf.Variable([n_dense_neurons])
print(b)

xW = tf.matmul(x,W)

z = tf.add(xW, tf.cast(b,tf.float32))

a = tf.tanh(z)

init = tf.compat.v1.global_variables_initializer()
sess.run(init )

layer_out = sess.run(a, feed_dict={x:np.random.random([1,n_features])})

print(layer_out)







<tf.Variable 'Variable_76:0' shape=(1,) dtype=int32>
[[ 0.9659712   0.96366465 -0.47413892]]
