# **Learn Tensorflow**

In [2]:
print('Tensorflow')

Tensorflow


In [3]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

hello = tf.constant("Hellooooooooooooo ")
world = tf.constant("World! ")

type (hello)

sess = tf.compat.v1.Session()
result = sess.run(hello+world)

result

b'Hellooooooooooooo World! '

In [7]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

a = tf.constant(10)
b = tf.constant(450)
sess = tf.compat.v1.Session()
result = sess.run(a+b)
result

460

In [26]:
const = tf.constant(10)

fill_mat = tf.fill( (4,4), 10)

fill_zero = tf.zeros((4,4))

myrandn = tf.random.normal((4,4), mean = 2, stddev =0.5)

my_ops = [const, fill_mat, fill_zero, myrandn]

sess = tf.compat.v1.Session()
result = sess.run(const)
result


10

In [18]:
sess = tf.compat.v1.Session()
result = sess.run(fill_mat )
result

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)

In [19]:
sess = tf.compat.v1.Session()
result = sess.run(fill_zero)
result

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [27]:
sess = tf.compat.v1.Session()
result = sess.run(myrandn)
result

array([[1.1881309, 2.546825 , 2.0361106, 2.0137334],
       [2.539907 , 2.474639 , 2.2981424, 3.2171803],
       [2.0480635, 2.4358706, 1.7014809, 2.3479867],
       [1.4695742, 0.9597193, 2.6892915, 2.066409 ]], dtype=float32)