<a href="https://colab.research.google.com/github/mamud1977/bootup/blob/main/my_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensorflow.....**

In [2]:
print('Tensorflow')

Tensorflow


In [3]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

hello = tf.constant("Hellooooooooooooo ")
world = tf.constant("World! ")

type (hello)

sess = tf.compat.v1.Session()
result = sess.run(hello+world)

result

b'Hellooooooooooooo World! '

In [7]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

a = tf.constant(10)
b = tf.constant(450)
sess = tf.compat.v1.Session()
result = sess.run(a+b)
result

460

In [28]:
const = tf.constant(10)

fill_mat = tf.fill( (4,4), 10)

fill_zero = tf.zeros((4,4))

myrandn = tf.random.normal((4,4), mean = 2, stddev =0.5)

my_ops = [const, fill_mat, fill_zero, myrandn]

sess = tf.compat.v1.Session()
result = sess.run(const)
result


10

In [18]:
sess = tf.compat.v1.Session()
result = sess.run(fill_mat )
result

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)

In [19]:
sess = tf.compat.v1.Session()
result = sess.run(fill_zero)
result

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [27]:
sess = tf.compat.v1.Session()
result = sess.run(myrandn)
result

array([[1.1881309, 2.546825 , 2.0361106, 2.0137334],
       [2.539907 , 2.474639 , 2.2981424, 3.2171803],
       [2.0480635, 2.4358706, 1.7014809, 2.3479867],
       [1.4695742, 0.9597193, 2.6892915, 2.066409 ]], dtype=float32)

In [35]:
a = tf.constant([[1,2],
                [3,4],
                 [4,6]])

b = tf.constant([[7,2,8],
                [3,4,1]])

result = tf.matmul(a,b)

sess = tf.compat.v1.Session()
result = sess.run(tf.matmul(a,b))
result

array([[13, 10, 10],
       [33, 22, 28],
       [46, 32, 38]], dtype=int32)

In [52]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

n1 = tf.constant(3)
n2 = tf.constant(4)

n3 = n1 +  n2

sess = tf.compat.v1.Session()
result = sess.run(n3)
result

g = tf.Graph()
print (g)

graph1 = tf.compat.v1.get_default_graph()
print (graph1)

graph2 = tf.Graph()
print (graph2)

with graph2.as_default():
  print(graph2 is tf.compat.v1.get_default_graph())

print(graph2 is tf.compat.v1.get_default_graph())

True
False


**Variables & Placeholders**

In [57]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

my_tensor = tf.random.uniform((4,4),minval=0, maxval =1, dtype='float16')

sess = tf.compat.v1.Session()
result = sess.run(my_tensor)
result




array([[0.167 , 0.957 , 0.4297, 0.3428],
       [0.0293, 0.8594, 0.705 , 0.623 ],
       [0.3418, 0.2197, 0.3623, 0.4434],
       [0.2764, 0.2295, 0.254 , 0.7754]], dtype=float16)