<a href="https://colab.research.google.com/github/mamud1977/bootup/blob/main/tensorflow%202.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensorflow 2.0.....**

In [ ]:
# !pip install tensorflow-gpu==2.8.4

In [23]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.17.0


## TF Constant.....

In [24]:
tf_const = tf.constant(10)
x = tf_const.numpy()
print(f'TF Constant-Scalar: Shape{tf_const.shape}')
print(x)


tf_const = tf.constant(["a","b","c","d","e"])
x = tf_const.numpy()
print(f'TF Constant-vector: Shape{tf_const.shape}')
print(x)

tf_const = tf.constant([[1,2,5],[3,4,7]])
x = tf_const.numpy()
print(f'TF Constant-matrix: Shape{tf_const.shape}')
print(x)

tf_const = tf.constant([
                        [[1,2,5],[3,4,7]],
                        [[1,2,5],[3,6,7]],
                        [[1,5,5],[3,4,7]],
                        [[1,1,5],[3,9,7]],
                        [[1,1,5],[3,9,7]],
                        [[1,1,5],[3,9,7]]
                       ])
x = tf_const.numpy()
print(f'TF Constant-matrix: Shape{tf_const.shape}') #6,2,3
print(x)


TF Constant-Scalar: Shape()
10
TF Constant-vector: Shape(5,)
[b'a' b'b' b'c' b'd' b'e']
TF Constant-matrix: Shape(2, 3)
[[1 2 5]
 [3 4 7]]
TF Constant-matrix: Shape(6, 2, 3)
[[[1 2 5]
  [3 4 7]]

 [[1 2 5]
  [3 6 7]]

 [[1 5 5]
  [3 4 7]]

 [[1 1 5]
  [3 9 7]]

 [[1 1 5]
  [3 9 7]]

 [[1 1 5]
  [3 9 7]]]


## Slicing...

In [30]:
x = tf_const[2:4,1,1:3]
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 7],
       [9, 7]], dtype=int32)>

## Reshaping...

In [31]:
tf_const = tf.constant([
                        [[1,2,5],[3,4,7]],
                        [[1,2,5],[3,6,7]],
                        [[1,5,5],[3,4,7]],
                        [[1,1,5],[3,9,7]],
                        [[1,1,5],[3,9,7]],
                        [[1,1,5],[3,9,7]]
                       ])

tf_const = tf.reshape(tf_const,[6,6])
tf_const

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[1, 2, 5, 3, 4, 7],
       [1, 2, 5, 3, 6, 7],
       [1, 5, 5, 3, 4, 7],
       [1, 1, 5, 3, 9, 7],
       [1, 1, 5, 3, 9, 7],
       [1, 1, 5, 3, 9, 7]], dtype=int32)>

In [32]:
tf_const = tf.constant([1,2,3,4,5,6,7,8,9,10,11,12])
tf_const = tf.reshape(tf_const,[3,4])
tf_const

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)>

## TF Variable....

In [101]:
tf_var1 = tf.Variable([[1,3,5], [2,4,6]],name='initial-1',)
tf_var2 = tf.Variable([[10,30,50], [20,40,60]],name='initial-2',)
print(tf_var1)
print(tf_var2)

tf_var = tf.add(tf_var1, tf_var2)
print(tf_var)

tf_var = tf.subtract(tf_var, tf_var2)
print(tf_var)

<tf.Variable 'initial-1:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>
<tf.Variable 'initial-2:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 30, 50],
       [20, 40, 60]], dtype=int32)>
tf.Tensor(
[[11 33 55]
 [22 44 66]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [102]:
tf_var = tf.Variable([[1,3,5], [2,4,6]],name='initial-1',)
print(tf_var)

tf_var = tf_var.assign_add([[1,1,1], [2,2,2]])
print(tf_var)

tf_var = tf_var.assign_sub([[1,1,1], [2,2,2]])
print(tf_var)

## dimension to remain the same
tf_var = tf_var.assign([[10,30,50], [20,40,60]])
print(tf_var)

<tf.Variable 'initial-1:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[2, 4, 6],
       [4, 6, 8]], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[10, 30, 50],
       [20, 40, 60]], dtype=int32)>


## MATMUL Operation...

In [107]:
w = tf.constant([
                [1,2,3],
                [4,5,6],
                [2,5,8]
                ])
print(f'w({w.shape}):\n{w}')

x = tf.Variable([
                [1],
                [2],
                [3]
                ])
print(f'x({x.shape}):\n{x}')

y = tf.matmul(w,x)
print(f'y({y.shape}):\n{y}')

w((3, 3)):
[[1 2 3]
 [4 5 6]
 [2 5 8]]
x((3, 1)):
<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>
y((3, 1)):
[[14]
 [32]
 [36]]
