<a href="https://colab.research.google.com/github/mamud1977/bootup/blob/main/tensorflow%202.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensorflow 2.0.....**

In [ ]:
# !pip install tensorflow-gpu==2.8.4

In [23]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.17.0


## TF Constant.....

In [24]:
tf_const = tf.constant(10)
x = tf_const.numpy()
print(f'TF Constant-Scalar: Shape{tf_const.shape}')
print(x)


tf_const = tf.constant(["a","b","c","d","e"])
x = tf_const.numpy()
print(f'TF Constant-vector: Shape{tf_const.shape}')
print(x)

tf_const = tf.constant([[1,2,5],[3,4,7]])
x = tf_const.numpy()
print(f'TF Constant-matrix: Shape{tf_const.shape}')
print(x)

tf_const = tf.constant([
                        [[1,2,5],[3,4,7]],
                        [[1,2,5],[3,6,7]],
                        [[1,5,5],[3,4,7]],
                        [[1,1,5],[3,9,7]],
                        [[1,1,5],[3,9,7]],
                        [[1,1,5],[3,9,7]]
                       ])
x = tf_const.numpy()
print(f'TF Constant-matrix: Shape{tf_const.shape}') #6,2,3
print(x)


TF Constant-Scalar: Shape()
10
TF Constant-vector: Shape(5,)
[b'a' b'b' b'c' b'd' b'e']
TF Constant-matrix: Shape(2, 3)
[[1 2 5]
 [3 4 7]]
TF Constant-matrix: Shape(6, 2, 3)
[[[1 2 5]
  [3 4 7]]

 [[1 2 5]
  [3 6 7]]

 [[1 5 5]
  [3 4 7]]

 [[1 1 5]
  [3 9 7]]

 [[1 1 5]
  [3 9 7]]

 [[1 1 5]
  [3 9 7]]]


## Slicing...

In [30]:
x = tf_const[2:4,1,1:3]
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 7],
       [9, 7]], dtype=int32)>

## Reshaping...

In [31]:
tf_const = tf.constant([
                        [[1,2,5],[3,4,7]],
                        [[1,2,5],[3,6,7]],
                        [[1,5,5],[3,4,7]],
                        [[1,1,5],[3,9,7]],
                        [[1,1,5],[3,9,7]],
                        [[1,1,5],[3,9,7]]
                       ])

tf_const = tf.reshape(tf_const,[6,6])
tf_const

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[1, 2, 5, 3, 4, 7],
       [1, 2, 5, 3, 6, 7],
       [1, 5, 5, 3, 4, 7],
       [1, 1, 5, 3, 9, 7],
       [1, 1, 5, 3, 9, 7],
       [1, 1, 5, 3, 9, 7]], dtype=int32)>

In [ ]:

print('TF Variable.....')
tensor_var = tf.Variable([[23,44,55],[333,33,7]])
print('Initial :',tensor_var)

tensor_var = tensor_var[1,2].assign(200)
print('Updated :',tensor_var)

tf_c = tf.constant([[1,2],[3,4]])
print('Initial constant:',tf_c)

tf_c = tf_c + 10

print('Initial + 10 :',tf_c)

tf_c = tf_c * 2
print('Mult:',tf_c)

tf_c = tf.constant([[1,2],[3,4]])
tf_c =np.square(tf_c)
print('Square:',tf_c)

tf_c =np.sqrt(tf_c)
print('Sqrt:',tf_c)

tf_c =np.log(tf_c)
print('Log:',tf_c)



tfv1 = tf.Variable([[1,2],[3,4]])
tfv2 = tf.Variable([[2,0],[1,1]])


print('Dot product of two tensor:')
y = np.dot(tfv1, tfv2)
print(y)

s = tf.constant('Hello World!!!')
print('Length:',tf.strings.length(s))
print("Unicode Decode:",tf.strings.unicode_decode(s,"UTF8"))


tf_array = tf.constant(["Big","Class","Room"])

for s in tf_array:
  print(s)
  print(type(s))

In [ ]:
import tensorflow as tf
import numpy as np
import datetime
from tensorflow.keras.datasets import fashion_mnist

(X_train,Y_train), (X_test, Y_test) = fashion_mnist.load_data()

X_train = X_train/255.0
X_test = X_test/255.0

print('Initial Shape:',X_train.shape)
# (60000, 28, 28)

X_train = X_train.reshape(-1,28*28)
X_test = X_test.reshape(-1,28*28)

print('After flatenning:',X_train.shape)

model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(units=128,activation='relu',input_shape=(784,)))
model.add(tf.keras.layers.Dense(units=10,activation='softmax'))

model.compile(optimizer='adam', loss = 'sparse_categorical_crossentropy',metrics=['sparse_categorical_accuracy'])


model.summary()

model.fit(X_train, Y_train, epochs=5)

Initial Shape: (60000, 28, 28)
After flatenning: (60000, 784)
Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_20 (Dense)            (None, 128)               100480    
                                                                 
 dense_21 (Dense)            (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.5018 - sparse_categorical_accuracy: 0.8238
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3765 - sparse_categorical_accuracy: 0.8620
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3402 - sparse_categorical_accuracy: 0.8759
Epoch 4/5
1875/1875 [

In [ ]:
test_loss, test_accuracy = model.evaluate(X_test, Y_test)

print('Test loss {}'.format(test_loss))
print('Test Accuracy {}'.format(test_accuracy))

313/313 [==============================] - 1s 3ms/step - loss: 0.3694 - sparse_categorical_accuracy: 0.8687
Test loss 0.3694240152835846
Test Accuracy 0.8687000274658203
