In [ ]:
print('Welcome to Numpy, the numerical python....')

Welcome to Numpy, the numerical python...


In [9]:
import numpy as np
my_list = [1,2,3,4,5]

my_list



[1, 2, 3, 4, 5]

In [12]:
my_array = np.array(my_list)

my_array

array([1, 2, 3, 4, 5])

In [44]:
my_array.max()

5

In [64]:
my_array2 = np.random.randint(0, 20, 30)
my_array2

my_array2.size
my_array3 = my_array2.reshape(5,6)
my_array3

array([[ 0, 10, 15,  1, 10, 11],
       [ 6, 16, 15, 17,  7,  5],
       [ 9, 13,  2, 10, 16,  6],
       [ 4,  8, 10,  2, 17, 12],
       [ 4,  2, 16, 15,  7,  6]])

In [65]:
my_array3[2,3]

10

In [67]:
my_array3[2,:]

array([ 9, 13,  2, 10, 16,  6])

In [70]:
my_array3[0:2,1:3]

array([[10, 15],
       [16, 15]])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.linspace(0,2,11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [40]:
np.random.randint(1,3.2)

1

In [41]:
np.random.randint(1,100,(3,3))

array([[55, 48, 55],
       [ 3, 45, 70],
       [48, 11, 98]])

In [43]:
np.random.randint(1,100,(3,4,5))

array([[[ 5, 51, 27, 31, 83],
        [63, 12, 17, 68, 67],
        [56, 74, 75,  5, 95],
        [48, 28, 42, 76, 52]],

       [[90, 22, 26, 51, 22],
        [ 4, 80, 82, 55, 58],
        [63, 82, 27,  9,  1],
        [27,  2, 39, 76, 97]],

       [[36, 94, 98, 78, 42],
        [39, 64, 41, 28, 78],
        [13, 52, 67, 69, 66],
        [48, 15, 33, 84, 70]]])